require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Enabled: false
  IgnoredPatterns: ['\#.*'] # ignore long comments

Style/ParallelAssignment:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/LambdaCall:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/BlockDelimiters:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Enabled: false