cache: bundler
language: ruby
rvm:
  - "2.3.0"
  - "2.4.0"
  - "2.5.0"
  - "2.6.0"
  - ruby-head
  - jruby-9.2.5.0
matrix:
  allow_failures:
    # Some RVM problems with fetching it?..
    - jruby-9.2.5.0
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
